/*
 * WARNING: This file is automatically generated. DO NOT MODIFY unless you know what you're doing.
 *
 * If you wish to regenerate this file because of a game update use the ZHMTools ModuleInfoParser tool:
 * https://github.com/OrfeasZ/ZHMTools/releases
 */

#pragma once

#include <cstdint>
#include <unordered_map>
#include <string>

class HMAData
{
public:
	static std::unordered_map<uint32_t, std::string> PropertyNames;
	static std::unordered_map<std::string, std::unordered_map<std::string, int32_t>> Enums;
};
